total_condition_statements = {":intermediaryORplatform": 'Are you an intermediary or platform?',
 ":useAIModelLLMGenerativeAISoftwareAlgorithm": 'Do you use Artificial Intelligence model(s) /LLM/Generative AI, software(s) or algorithm(s)',
 ":CResource": 'Do you permit the use of AI model(s) on or through your computer resource',
 ":user": 'Do you have users?',
 ":PermitsORfacilitates": 'Do you permit or facilitate synthetic creation, generation or modification of a text, audio, visual or audio-visual information through your software or computer resource?',
 ":misinformationDeepfake": 'in such a manner that such information may be used potentially as misinformation or deepfake?',
 ":nonCompliance": 'Are you in non-compliance of the provisions of the IT Act and/or IT Rules'}

total_obligation_statements = {"paragraph2": 'All intermediaries or platforms to ensure that use of Artificial Intelligence model(s) /LLM/Generative AI, software(s) or algorithm(s)on or through its computer resource does not permit its users to host, display, upload, modify, publish, transmit, store, update or share any unlawful content as outlined in the Rule 3(1)(b) of the IT Rules or violate any other provision of the IT Act.',
                               "paragraph3": 'All intermediaries or platforms to ensure that their computer resource do not permit any bias or discrimination or threaten the integrity of the electoral process including via the use of Artificial Intelligence model(s)/LLM/Generative AI, software(s) or algorithm(s).',
                               "paragraph4": 'The use of under-testing / unreliable Artificial Intelligence model(s) /LLM/Generative AI, software(s) or algorithm(s) and its availability to the users on Indian Internet must be done so with explicit permission of the Government of India and be deployed only after appropriately labeling the possible and inherent fallibility or unreliability of the output generated. Further, ‘consent popup’ mechanism may be used to explicitly inform the users about the possible and inherent fallibility or unreliability of the output generated.',
                               "paragraph5": 'All users must be clearly informed including through the terms of services and user agreements of the intermediary or platforms about the consequence of dealing with the unlawful information on its platform, including disabling of access to or removal of non-compliant information, suspension or termination of access or usage rights of the user to their user account, as the case may be, and punishment under applicable law.',
                               "paragraph6": 'Where any intermediary through its software or any other computer resource permits or facilitates synthetic creation, generation or modification of a text, audio, visual or audio-visual information, in such a manner that such information may be used potentially as misinformation or deepfake, it is advised that such information created, generated, or modified through its software or any other computer resource is labeled or embedded with a permanent unique metadata or identifier, by whatever name called, in a manner that such label, metadata or identifier can be used to  identify that such information has been created, generated or modified using computer resource of the intermediary, or identify the user of the software or such other computer resource, the intermediary through whose software or such other computer resource such information has been created, generated or modified and the creator or first originator of such misinformation or deepfake.',
                               "paragraph7": 'It is reiterated that non-compliance to the provisions of the IT Act and/or IT Rules would result in potential penal consequences to the intermediaries or platforms or its users when identified, including but not limited to prosecution under IT Act and several other statues of the criminal code.',
                               "paragraph8": 'All intermediaries are, hereby requested to ensure compliance with the above with immediate effect and to submit an Action Taken-cum-Status Report to the Ministry within 15 days of this advisory.'}

extra_conditions = {"Intermediary": 'Are you an intermediary?',
                    "Platform": 'Are you a platform?',
                    "Under testing": 'Is your product under testing?'}